# Generated by Django 5.2.17 on 2026-08-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "ats_provider",
                    models.CharField(
                        choices=[
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("gupy", "Gupy"),
                            ("outro", "Outro / desconhecido"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "ats_board_url",
                    models.URLField(
                        blank=True,
                        help_text="URL/identificador do board no ATS (ex.: token do Greenhouse/Lever/Ashby).",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                (
                    "auto_promoted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="RF-02.4 — promoção automática de tier (válida por 30 dias).",
                        null=True,
                    ),
                ),
                ("careers_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("poll_error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_slot",
                    models.CharField(
                        choices=[
                            ("R1", "R1"),
                            ("R2", "R2"),
                            ("R3", "R3"),
                            ("R4", "R4"),
                        ],
                        max_length=2,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("backlog", "Backlog (segunda-feira)"),
                            ("reduzido", "Reduzido (fim de semana)"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("companies_polled", models.PositiveIntegerField(default=0)),
                ("jobs_found", models.PositiveIntegerField(default=0)),
                ("jobs_scored", models.PositiveIntegerField(default=0)),
                (
                    "dossiers_generated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sempre 0 nesta fase — geração de dossiê é Fase 3.",
                    ),
                ),
                ("dossiers_failed", models.PositiveIntegerField(default=0)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em execução"),
                            ("completed", "Concluída"),
                            ("completed_with_errors", "Concluída com erros"),
                            ("failed", "Falhou"),
                        ],
                        default="running",
                        max_length=25,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("work_model", models.CharField(blank=True, max_length=100)),
                ("seniority", models.CharField(blank=True, max_length=100)),
                ("description_raw", models.TextField(blank=True)),
                (
                    "description_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("url_apply", models.URLField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("gupy", "Gupy"),
                            ("indeed", "Indeed"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_at_estimated", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("score", models.SmallIntegerField(blank=True, null=True)),
                ("score_rationale", models.TextField(blank=True)),
                ("gaps", models.JSONField(blank=True, default=list)),
                ("recruiter_score", models.SmallIntegerField(blank=True, null=True)),
                ("recruiter_rationale", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("knockouts", models.JSONField(blank=True, default=list)),
                ("boolean_string", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nova"),
                            ("radar", "Radar (fit parcial)"),
                            ("dossier_pending", "Aguardando dossiê (Fase 3)"),
                            ("rejected", "Reprovada"),
                            ("expired", "Expirada"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="radar.company",
                    ),
                ),
                (
                    "found_in_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_found_in",
                        to="radar.runlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at"],
                "indexes": [
                    models.Index(fields=["status"], name="radar_job_status_2be959_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "external_id"),
                        name="uniq_company_external_id",
                    )
                ],
            },
        ),
    ]
